name: CV - Auto Compile and Update
on:
  workflow_dispatch:
    # For manually trigger
  push:
    tags:
      - "v*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.DEPLOY_TOKEN }}
        persist-credentials: false
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: cv.tex
    - name: Check pdf file
      run: |
        file cv.pdf | grep -q ' PDF '
    - name: Get current date
      id: date
      run: |
        echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: CV-YuSHEN-${{ steps.date.outputs.date }}
        prerelease: false
        draft: false
        files: cv.pdf
        token: ${{ secrets.DEPLOY_TOKEN }}