name: CV - Auto Compile and Update
on:
  workflow_dispatch:
    # For manually trigger
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.DEPLOY_TOKEN }}
        persist-credentials: false
        fetch-depth: 0
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: cv.tex
    - name: Check pdf file
      run: |
        file cv.pdf | grep -q ' PDF '
    - name: Get current date
      id: date
      run: |
        echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body: CV-YuSHEN-${{ steps.date.outputs.date }}
        name: CV-YuSHEN-${{ steps.date.outputs.date }}
        prerelease: false
        draft: false
        files: cv.pdf
        token: ${{ secrets.DEPLOY_TOKEN }}